"""spread table

Revision ID: 485c62517429
Revises: 8b4d8fd6009a
Create Date: 2018-11-22 15:00:24.341281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485c62517429'
down_revision = '8b4d8fd6009a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spread')
    # ### end Alembic commands ###
