"""weeks table

Revision ID: a4dcaddcb4f0
Revises: dce0e74920fb
Create Date: 2018-11-24 12:59:20.748859

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from datetime import timedelta


# revision identifiers, used by Alembic.
revision = 'a4dcaddcb4f0'
down_revision = 'dce0e74920fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    week_table = op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    insert_json = []
    end_date = datetime.strptime('20 Nov 2018', '%d %b %Y')
    for week_number in range(12,22):
        date = end_date
        end_date = date + timedelta(days=7)
        week_hash = {
            'year': 2018,
            'week_number': week_number,
            'start_date': date,
            'end_date': end_date
        }
        insert_json.append(week_hash)

    op.bulk_insert(week_table, insert_json)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week')
    # ### end Alembic commands ###
